# Generated by Django 4.0.10 on 2023-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('question_1', models.TextField()),
                ('answer_1', models.BooleanField()),
                ('question_2', models.TextField()),
                ('answer_2', models.IntegerField()),
                ('question_3', models.TextField()),
                ('answer_3', models.IntegerField()),
                ('question_4', models.TextField()),
                ('answer_4', models.IntegerField()),
                ('question_5', models.TextField()),
                ('answer_5', models.IntegerField()),
                ('question_6', models.TextField()),
                ('answer_6', models.IntegerField()),
                ('question_7', models.TextField()),
                ('answer_7', models.IntegerField()),
                ('question_8', models.TextField()),
                ('answer_8', models.IntegerField()),
                ('question_9', models.TextField()),
                ('answer_9', models.IntegerField()),
                ('question_10', models.TextField()),
                ('answer_10', models.IntegerField()),
                ('question_11', models.TextField()),
                ('answer_11', models.IntegerField()),
                ('question_12', models.TextField()),
                ('answer_12', models.BooleanField()),
                ('question_13', models.TextField()),
                ('answer_13', models.IntegerField()),
                ('question_14', models.TextField()),
                ('answer_14', models.IntegerField()),
                ('question_15', models.TextField()),
                ('answer_15', models.IntegerField()),
                ('question_16', models.TextField()),
                ('answer_16', models.IntegerField()),
                ('question_17', models.TextField()),
                ('answer_17', models.IntegerField()),
                ('question_18', models.TextField()),
                ('answer_18', models.IntegerField()),
                ('question_19', models.TextField()),
                ('answer_19', models.IntegerField()),
                ('question_20', models.TextField()),
                ('answer_20', models.IntegerField()),
                ('question_21', models.TextField()),
                ('answer_21', models.IntegerField()),
                ('question_22', models.TextField()),
                ('answer_22', models.IntegerField()),
                ('question_23', models.TextField()),
                ('answer_23', models.IntegerField()),
                ('question_24', models.TextField()),
                ('answer_24', models.IntegerField()),
                ('question_25', models.TextField()),
                ('answer_25', models.TextField()),
                ('question_26', models.TextField()),
                ('answer_26', models.TextField()),
                ('question_27', models.TextField()),
                ('answer_27', models.TextField()),
                ('question_28', models.TextField()),
                ('answer_28', models.TextField()),
            ],
        ),
    ]
